author: Daniel Owsianski (daniel-at-jarmark-d0t-org)
author: Nate Walker (kiwinewt-at-gmail-dot-com)
summary: Application specific configuration in pure old Rails style.
homepage: http://kiwinewt.geek.nz/appconfig-plugin/
plugin: git@github.com:kiwinewt/app_config.git
license: MIT
version: 0.1
rails_version: 1.0.0+
